# Generated by Django 2.2.14 on 2020-08-05 08:33

from django.db import migrations, models
import estore.models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True, verbose_name=estore.models.Product)),
                ('description', models.CharField(max_length=100, null=True, verbose_name=estore.models.Product)),
            ],
        ),
    ]
