# Generated by Django 2.2.14 on 2020-08-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_auto_20200805_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MP', 'Mobile Phones'), ('MAC', 'Apple Mac'), ('PC', 'PC'), ('GC', 'Game Consoles')], max_length=10, null=True),
        ),
    ]
